FROM python:3.11-slim-buster
ARG PIPENV_ARGS
ENV PIPENV_ARGS $PIPENV_ARGS

WORKDIR /app
COPY Pipfile .
COPY Pipfile.lock .
#RUN apt-get update && apt-get install -y gcc ffmpeg
#RUN apt-get update && apt-get install -y git
RUN pip install --no-cache-dir pipenv
RUN pipenv install --system ${PIPENV_ARGS}
COPY . .
CMD ["daphne", "-p 8080", "-b", "0.0.0.0", "RecipeBase.asgi:application"]