version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.django
        ports:
            - "8085:8080"
        volumes:
            - .:/app
        restart: unless-stopped # unless-stopped on-failure

    quasar:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.quasar
#          target: 'production-stage'
        ports:
            - '8086:80'
        volumes:
            - '.:/app'
            - './nginx.conf:/etc/nginx/nginx.conf'
        links:
            - "web:web"
        # command: [nginx-debug, '-g', 'daemon off;']
#        command: /bin/sh -c "yarn && quasar dev"

    qcluster:
        build: .
        restart: unless-stopped
        volumes:
            - ./:/app
        entrypoint: ["python3", "manage.py", "qcluster"]
