version: "3"
services:
    redis:
        image: redis:7-alpine
        volumes:
            - redis_data:/data
        restart: always

    web:
        build:
            context: .
            dockerfile: Dockerfile.django
        ports:
            - "${APP_PORT:-8085}:8080"
        volumes:
            - .:/app
        depends_on:
            - redis
        restart: unless-stopped # unless-stopped on-failure

    quasar:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile.quasar
#          target: 'production-stage'
        ports:
            - '${NGINX_PORT:-8086}:80'
        volumes:
            - '.:/app'
            - './nginx.conf:/etc/nginx/nginx.conf'
            - './logs:/var/log/nginx/server'
        links:
            - "web:web"
        healthcheck:
            test: "curl -m 5 http://localhost"
            interval: 5s
            timeout: 10s
            start_period: 10s
            retries: 3

    qcluster:
        build:
            context: .
            dockerfile: Dockerfile.django
        restart: unless-stopped
        volumes:
            - ./:/app
        entrypoint: ["python3", "manage.py", "qcluster"]

volumes:
    redis_data:
